#!/usr/bin/env bash
# ----------------------------------------------
# Script: generate_master_document.sh
# Purpose: Concatenate all AGI parts & appendices
# Usage: ./generate_master_document.sh
# ----------------------------------------------

# Output master filename
OUT="GAIA-QAO_AGI_Master_Full.md"

# List of source Markdown files (in desired order)
SOURCE_FILES=(
  "00_Framework_Overview.md"
  "01_Software_Technologies.md"
  "02_HIL_Thinking.md"
  "03_GQOIS_Object_ID.md"
  "04_Entangled_Accountability_Protocol.md"
  "05_Photonic_Sustainability_Loop.md"
  "06_QEP_Optical_Design.md"
  "07_Phase_1_Implementation_Roadmap.md"
  "08_QSI_Interactive_Calculator.md"
  "09_Implementation_Guidelines.md"
  "Appendix_A_ST_Codes.md"
  "Appendix_B_Diagrams.md"
  "Appendix_C_Templates.md"
  "CONTRIBUTING.md"
)

echo "Generating $OUT …"
echo "<!-- This file is autogenerated by generate_master_document.sh -->" > "$OUT"
echo "" >> "$OUT"

for file in "${SOURCE_FILES[@]}"; do
  if [[ -f "$file" ]]; then
    echo "Including $file"
    echo "" >> "$OUT"
    echo "<!-- ================= $file ================= -->" >> "$OUT"
    cat "$file" >> "$OUT"
    echo "" >> "$OUT"
  else
    echo "⚠️  Warning: $file not found, skipping."
  fi
done

echo "Done. Master document is at $OUT"

# Generate a printable PDF version of the master document using Pandoc
pandoc "$OUT" -o GAIA-QAO_AGI_Master_Full.pdf
