#!/usr/bin/env bash
# ----------------------------------------------
# Script: generate_master_document.sh
# Purpose: Concatenate all AGI parts & appendices
# Usage: ./generate_master_document.sh
# ----------------------------------------------

# Output master filename
OUT="GAIA-QAO_AGI_Master_Full.md"

# List of source Markdown files (in desired order)
SOURCE_FILES=(
  "00_Framework_Overview.md"
  "01_Software_Technologies.md"
  "02_HIL_Thinking.md"
  "03_GQOIS_Object_ID.md"
  "04_TopLevel_Object_Models.md"
  "05_Subsystem_Registry.md"
  "06_Configuration_Management.md"
  "07_Database_Schema.md"
  "08_GAIA-Q-UI_Spec.md"
  "09_Implementation_Guidelines.md"
  "Appendix_A_ST_Codes.md"
  "Appendix_B_ID_Examples.md"
  "Appendix_C_ERD.md"
  "Appendix_D_Use_Cases.md"
  "Appendix_E_Note.md"
  "Appendix_F_SSS_Codes.md"
  "Appendix_G_Templates.md"
)

echo "Generating $OUT …"
echo "<!-- This file is autogenerated by generate_master_document.sh -->" > "$OUT"
echo "" >> "$OUT"

for file in "${SOURCE_FILES[@]}"; do
  if [[ -f "$file" ]]; then
    echo "Including $file"
    echo "" >> "$OUT"
    echo "<!-- ================= $file ================= -->" >> "$OUT"
    cat "$file" >> "$OUT"
    echo "" >> "$OUT"
  else
    echo "⚠️  Warning: $file not found, skipping."
  fi
done

echo "Done. Master document is at $OUT"
